config/routes.rb
Rails.application.routes.draw do
  # get 'author/show'
  # get 'author/new'
  # get 'author/create'
  resources :authors

  # get 'articles/new'
  # get 'articles/index'
  resources :articles

  get 'statics/contact'
  get 'statics/us'

  get 'home/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author
  validates :titulo, presence: true
  validates :contenido, presence:  {message: "texto es requerido"}, length: {minimum: 50, message: "texto muy corto (minimo 50 caracteres)"}
end

app/models/author.rb
class Author < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    #show a list of record
    @articles = Article.all.order("created_at DESC")
  end

  def show
    # show a record
    @article = Article.find(params[:id])
  end

  def new
    # form to create
    @article = Article.new
  end

  def create
    # action for new record, executed by action 'new'
    @article = Article.new(article_params)
    @article.author_id = 1; # TODO: assignation auto, no manually
    if @article.save
      redirect_to action: 'show', id:@article.id
    else
      render action: "new"
    end
  end

  def edit
    # form to edit
  end

  def update
    # action to update, executed by action 'edit'
  end

  def destroy
    # action to delete
  end

  private 
  
  def article_params
    params[:article].permit(:titulo, :contenido)
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
  end

  def show
  end

  def new
    # form to create
    @author = Author.new
  end

  def create
    # action for new record, executed by action 'new'
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author 
    else
      render action: "new"
    end
  end

  def edit
    # form to edit
  end

  def update
    # action to update, executed by action 'edit'
  end

  def destroy
    # action to delete
  end

  private 
  
  def author_params
    params[:author].permit(:email, :nombre)
  end
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  def index
  end

  def show
  end

  def new
    # form to create
    @autor = Autor.new
  end

  def create
    # action for new record, executed by action 'new'
    @autor = Autor.new(autor_params)

    if @autor.save
      redirect_to @autor 
    else
      render action: "new"
    end
  end

  def edit
    # form to edit
  end

  def update
    # action to update, executed by action 'edit'
  end

  def destroy
    # action to delete
  end

  private 
  
  def autor_params
    params[:autor].permit(:email, :nombre)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def contact
    @id = params['id']
    @pagina = params['pagina']
  end

  def us
    @validador = true
    @usuarios = ['Franco', 'Leo', 'Pepillo']
    @mensaje = "Hola desde el controlle Statics"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>

<% @articles.each do |art| %>
<h2><%= link_to art.titulo, art %></h2>
<p><%= art.created_at.strftime("%d/%m/%Y") %></p>
<p><%= art.contenido.truncate_words(30) %></p>
<% end %>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

<%= form_for @article, url: {action: "create"} do |f| %>

<% if @article.errors.any? %>
<div id="errors">
  <h2>Oops! please check this to continue:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= f.label :titulo %> <br>
<%= f.text_field :titulo %> <br>

<%= f.label :contenido %> <br>
<%= f.text_area :contenido %> <br>

<%= f.submit "Crear Artículo" %>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.titulo %></h1>

<p>Creado el <%= @article.created_at.strftime("%d/%m/%Y") %></p>

<p><%= @article.contenido %></p>

app/views/authors/create.html.erb
<h1>Author#create</h1>
<p>Find me in app/views/author/create.html.erb</p>

app/views/authors/index.html.erb
<h1>Author#index</h1>
<p>Find me in app/views/author/index.html.erb</p>

app/views/authors/new.html.erb
<h1>Author#new</h1>
<p>Find me in app/views/author/new.html.erb</p>

<%= form_for @author, url: {action: "create"} do |f| %>
<%= f.label :nombre %> <br>
<%= f.text_field :nombre %> <br>

<%= f.label :email %> <br>
<%= f.text_field :email %> <br>

<%= f.submit "Crear Author" %>
<% end %>

app/views/authors/show.html.erb
<h1>Author#show</h1>
<p>Find me in app/views/author/show.html.erb</p>

app/views/home/index.html.erb
<% provide(:title, 'Home') %>
<h1>Home</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'shared/header' %>
  <%= yield %>
</body>

</html>

app/views/shared/_header.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Contact', statics_contact_path %>
<%= link_to 'Us', statics_us_path %>

app/views/statics/contact.html.erb
<% content_for(:title, 'Contact Me') %>

<h1>Contact</h1>
<p>Find me in app/views/statics/contact.html.erb</p>

<%= params.inspect  %>
<p> ID: <%= params['id']  %></p>
<p> PAGE: <%= params['pagina']  %></p>

<br>

<%= params.inspect  %>
<p> ID: <%= @id  %></p>
<p> PAGE: <%= @page  %></p>

<br>

app/views/statics/us.html.erb
<% provide(:title, 'Us') %>

<h1>Us</h1>
<p>Find me in app/views/statics/us.html.erb</p>
<%= @mensaje %>
<br>
<%= "Este es el mensaje: #{@mensaje}" %>

<br>

<% if  @validador == true %>
<h1>Validador es verdadero</h1>
<% end %>

<br>

<ul>
  <% @usuarios.each do |usr| %>
    <%= "<li> #{usr} </li>".html_safe %>
  <% end %>
</ul>